//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PivotGrid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PivotGridResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PivotGridResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PivotGrid.PivotGridResource", typeof(PivotGridResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to set up the proprties of the pivot grid cells.
        /// </summary>
        public static string PivotGridCustomization_Caption {
            get {
                return ResourceManager.GetString("PivotGridCustomization_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotTable Customization.
        /// </summary>
        public static string PivotGridCustomization_Name {
            get {
                return ResourceManager.GetString("PivotGridCustomization_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the capabilities of editing the cube metadata inside the pivot grid.
        /// </summary>
        public static string PivotGridUpdateable_Caption {
            get {
                return ResourceManager.GetString("PivotGridUpdateable_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotTable with Updateable.
        /// </summary>
        public static string PivotGridUpdateable_Name {
            get {
                return ResourceManager.GetString("PivotGridUpdateable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the capabilities of custom styling of the pivot grid cells.
        /// </summary>
        public static string PivotGridWithStyle_Caption {
            get {
                return ResourceManager.GetString("PivotGridWithStyle_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotTable and Cell Styles.
        /// </summary>
        public static string PivotGridWithStyle_Name {
            get {
                return ResourceManager.GetString("PivotGridWithStyle_Name", resourceCulture);
            }
        }
    }
}
