//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdxDynamic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DemoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MdxDynamic.DemoResources", typeof(DemoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to initialize the dynamic pivot grid based on certain data parameters.
        /// </summary>
        public static string InitByTuple_Caption {
            get {
                return ResourceManager.GetString("InitByTuple_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotTable with Initialize by Tuple.
        /// </summary>
        public static string InitByTuple_Name {
            get {
                return ResourceManager.GetString("InitByTuple_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the capabilities of filtering metadata in the dynamic pivot grid.
        /// </summary>
        public static string MetadataFiltered_Caption {
            get {
                return ResourceManager.GetString("MetadataFiltered_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotTable with Metadata Filtered.
        /// </summary>
        public static string MetadataFiltered_Name {
            get {
                return ResourceManager.GetString("MetadataFiltered_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to generate a multi-page report by means of the dynamic pivot grid.
        /// </summary>
        public static string Overview_Caption {
            get {
                return ResourceManager.GetString("Overview_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotTable with Multi-page.
        /// </summary>
        public static string Overview_Name {
            get {
                return ResourceManager.GetString("Overview_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the capabilities of settings a visual representation of the PivotTable.
        /// </summary>
        public static string Tuning_Caption {
            get {
                return ResourceManager.GetString("Tuning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizing the PivotTable.
        /// </summary>
        public static string Tuning_Name {
            get {
                return ResourceManager.GetString("Tuning_Name", resourceCulture);
            }
        }
    }
}
