//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdxDesigner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MdxDesignerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MdxDesignerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MdxDesigner.MdxDesignerResource", typeof(MdxDesignerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;MdxLayoutWrapper xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Id&gt;accf213d-d310-4180-a5d4-0c2e6d547ec0&lt;/Id&gt;
        ///  &lt;LayoutName&gt;AW_Sparkline_2007year&lt;/LayoutName&gt;
        ///  &lt;CubeName&gt;Adventure Works&lt;/CubeName&gt;
        ///  &lt;SubCubeGlobal /&gt;
        ///  &lt;HasChanges&gt;None&lt;/HasChanges&gt;
        ///  &lt;MDXQuery&gt;WITH 
        ///MEMBER [Internet Gross Profit Dynamic] AS IIF(
        ///NonEmpty([Set All Month], ([Date].[Calendar].CurrentMember,[Measures].[Internet Gross Profit] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AW_Sparkline_2007year {
            get {
                return ResourceManager.GetString("AW_Sparkline_2007year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the dynamic pivot grid capabilities in OLAP data visualization.
        /// </summary>
        public static string Overview_Caption {
            get {
                return ResourceManager.GetString("Overview_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotTable with Cube choice.
        /// </summary>
        public static string Overview_Name {
            get {
                return ResourceManager.GetString("Overview_Name", resourceCulture);
            }
        }
    }
}
