//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Choices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChoicesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChoicesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Choices.ChoicesResource", typeof(ChoicesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the control used to select cubes.
        /// </summary>
        public static string CubeChoices_Caption {
            get {
                return ResourceManager.GetString("CubeChoices_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Choice.
        /// </summary>
        public static string CubeChoices_Name {
            get {
                return ResourceManager.GetString("CubeChoices_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the control used to select particular date from the cube Time dimension.
        /// </summary>
        public static string DatePicker_Caption {
            get {
                return ResourceManager.GetString("DatePicker_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Picker Widget.
        /// </summary>
        public static string DatePicker_Name {
            get {
                return ResourceManager.GetString("DatePicker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the dual slider control used to specify a range of values.
        /// </summary>
        public static string DualSlider_Caption {
            get {
                return ResourceManager.GetString("DualSlider_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Slider Widget.
        /// </summary>
        public static string DualSlider_Name {
            get {
                return ResourceManager.GetString("DualSlider_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the control that selects the cube measures.
        /// </summary>
        public static string MeasureChoices_Caption {
            get {
                return ResourceManager.GetString("MeasureChoices_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Choice Widget.
        /// </summary>
        public static string MeasureChoices_Name {
            get {
                return ResourceManager.GetString("MeasureChoices_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the control used to pick particular member(s) from a cube dimension.
        /// </summary>
        public static string MemberChoices_Caption {
            get {
                return ResourceManager.GetString("MemberChoices_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Choice.
        /// </summary>
        public static string MemberChoices_Name {
            get {
                return ResourceManager.GetString("MemberChoices_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the capability to limit members, available for picking from a cube dimension, with subselect..
        /// </summary>
        public static string MemberChoicesSubcube_Caption {
            get {
                return ResourceManager.GetString("MemberChoicesSubcube_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Choice Customization.
        /// </summary>
        public static string MemberChoicesSubcube_Name {
            get {
                return ResourceManager.GetString("MemberChoicesSubcube_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the filter used on members of a cube dimension based on their properties.
        /// </summary>
        public static string MemberFilterChoices_Caption {
            get {
                return ResourceManager.GetString("MemberFilterChoices_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice with Filter by Properties.
        /// </summary>
        public static string MemberFilterChoices_Name {
            get {
                return ResourceManager.GetString("MemberFilterChoices_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the controls for picking cubes, dimesions, hierarchies, and levels..
        /// </summary>
        public static string OverviewChoice_Caption {
            get {
                return ResourceManager.GetString("OverviewChoice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Metadata Choice.
        /// </summary>
        public static string OverviewChoice_Name {
            get {
                return ResourceManager.GetString("OverviewChoice_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the controls for picking cubes, dimesions, hierarchies, and levels..
        /// </summary>
        public static string PopupChoices_Caption {
            get {
                return ResourceManager.GetString("PopupChoices_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Metadata Popup Choice.
        /// </summary>
        public static string PopupChoices_Name {
            get {
                return ResourceManager.GetString("PopupChoices_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates the control that selects members from the cube dimension and presents them as a table of buttons.
        /// </summary>
        public static string Slicer_Caption {
            get {
                return ResourceManager.GetString("Slicer_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slicer Widget.
        /// </summary>
        public static string Slicer_Name {
            get {
                return ResourceManager.GetString("Slicer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT NON EMPTY HIERARCHIZE(CrossJoin(HIERARCHIZE({&lt;%SalesReason%&gt;}), {[Measures].[Internet Sales Amount], [Measures].[Internet Gross Profit]})) DIMENSION PROPERTIES PARENT_UNIQUE_NAME , HIERARCHY_UNIQUE_NAME , CUSTOM_ROLLUP , UNARY_OPERATOR , KEY0 ON 0 
        ///, NON EMPTY HIERARCHIZE(HIERARCHIZE([Customer].[Customer Geography].[Country].Members)) DIMENSION PROPERTIES PARENT_UNIQUE_NAME , HIERARCHY_UNIQUE_NAME , CUSTOM_ROLLUP , UNARY_OPERATOR , KEY0 ON 1
        ///FROM ( SELECT ( { &lt;%DateCalendarYear%&gt; }, { &lt;%ProductCate [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SlicerQuery {
            get {
                return ResourceManager.GetString("SlicerQuery", resourceCulture);
            }
        }
    }
}
